[package]
name = "e11_global_data"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition.workspace = true

[dependencies]
serenity = { path = "../../" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
